### ISSUE TITLE
'Value cannot be null. Parameter name: serviceType'

### ISSUE THREAD

**Issue by softtechinfo2020** [baseeam/baseeam-web-app#17]
When  i have to click add button from Purchasing module->Contract got exception "System.ArgumentNullException: 'Value cannot be null.
Parameter name: serviceType'
"
![Event](https://user-images.githubusercontent.com/58630781/70686271-d8d80600-1cd1-11ea-9ddc-74e69bb5be18.png)

**Comment by nguyencongle** [comment]
can you create a work order, so I can be sure that you have setup workflow service correctly?

**Comment by softtechinfo2020** [comment]
Yes i have setup workflow service correctly and  can able to create work Order.Only problem while click add button from Purchasing module->Contract
![Event](https://user-images.githubusercontent.com/58630781/70700301-89550280-1cf0-11ea-82eb-7930fee0e405.png)

**Comment by nguyencongle** [comment]
can you post the call stack?

**Comment by softtechinfo2020** [comment]
![Event](https://user-images.githubusercontent.com/58630781/70719457-0a73c000-1d18-11ea-8bfb-2a9bcb213d0c.png)

**Comment by nguyencongle** [comment]
can you step through the ContractController Create method to see in what line it will throw the exception?

**Comment by softtechinfo2020** [comment]
![Event](https://user-images.githubusercontent.com/58630781/70721813-4446c580-1d1c-11ea-9836-aa654b461790.png)

**Comment by nguyencongle** [comment]
you can go to the logs folder of Workflow Service to see if there's any exception

**Comment by softtechinfo2020** [comment]
Where to get logs folder?

**Comment by nguyencongle** [comment]
the folder that you install WorkflowService

**Comment by softtechinfo2020** [comment]
2019-12-12 20:30:29,837 [8] ERROR BaseEAM.Workflows.CustomWorkflowManager - System.ArgumentNullException: Value cannot be null.
Parameter name: serviceType
   at Autofac.Core.TypedService..ctor(Type serviceType)
   at Autofac.ResolutionExtensions.Resolve(IComponentContext context, Type serviceType)
   at BaseEAM.Core.Infrastructure.DependencyManagement.ContainerManager.Resolve(Type type, ILifetimeScope scope) in E:\BaseEAM\BaseEAM\BaseEAM.Core\Infrastructure\DependencyManagement\ContainerManager.cs:line 76
   at BaseEAM.Workflows.Activities.ActivityHelper.GetUsers(String methodSignature, Int64 entityId)
   at BaseEAM.Workflows.Activities.Task.Execute(CodeActivityContext context)
   at System.Activities.CodeActivity.InternalExecute(ActivityInstance instance, ActivityExecutor executor, BookmarkManager bookmarkManager)
   at System.Activities.ActivityInstance.Execute(ActivityExecutor executor, BookmarkManager bookmarkManager)
   at System.Activities.Runtime.ActivityExecutor.ExecuteActivityWorkItem.ExecuteBody(ActivityExecutor executor, BookmarkManager bookmarkManager, Location resultLocation)

**Comment by anandmask** [comment]
### I am also facing the same issue in Purchasing module->Contract.

**Comment by nguyencongle** [comment]
[ContractWorkflow.zip](https://github.com/baseeam/baseeam-web-app/files/3956424/ContractWorkflow.zip)

**Comment by nguyencongle** [comment]
unzip the file above we will have the .xaml file for ContractWorkflow.
Then go to WorkflowDefinition on UI to upload this new version.
For the Picture field, you can download the old one.

**Comment by anandmask** [comment]
That issue was fixed. Thanks a lot.

**Comment by softtechinfo2020** [comment]
Now issue has been resolved and Thanks for immediate response
